name: 部署网站
on:
  push:
    branches:
      main

jobs:
  deploy:
    name: 远程命令
    runs-on: ubuntu-latest
    steps:
    - name: 通过执行命令进行部署
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command: |
          cd /www/wwwroot/mcisee.top
          git pull origin
