name: 网站
on:
  push:
    branches:
      [ main ]

jobs:
  deploy:
    name: 远程部署
    runs-on: ubuntu-latest
    steps:
    - name: 执行远程命令
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        command: |
          echo ===============================================================
          cd /www/wwwroot/mcisee.top
          git pull origin
          echo ===============================================================
