name: Forum
run-name: Sync Data

on:
  schedule:
    - cron: 0 16 * * 0
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Handle files
        id: handle
        run: |
          git pull --rebase
          wget https://raw.githubusercontent.com/LYOfficial/BBSPK/refs/heads/main/res/data/forums.js
          mv forums.js scripts/lib/forums.js
          MESSAGE='modify: sync forums
          
          [Auto] Sync Forum Data'"
          (Time: `date +'%F %X %Z'`)"
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)  # To define the separator
          echo "message<<EOF"$'\n'"$MESSAGE"$'\n'EOF >> $GITHUB_OUTPUT  # For the multi-line output
      - name: Commit & Push
        id: commit_and_push
        uses: EndBug/add-and-commit@main
        with:
          default_author: github_actions
          message: ${{ steps.handle.outputs.message }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: Run remote commands
        id: run
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          command: |
            echo ===============================================================
            cd /www/wwwroot/mcisee.top
            git pull
            echo ===============================================================
