name: Launcher
run-name: Update Version
on:
  schedule:
    - cron: 0 0 */ * *

jobs:
  get:
    name: Get Launcher Version
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - subtitle: HMCL
            url: https://github.com/HMCL-dev/HMCL
          - subtitle: XMCL
            url: https://github.com/Voxelum/x-minecraft-launcher
    steps:
      - uses: actions/checkout@main
      - name: Get ${{ matrix.subtitle }} Version & Update launcher.js
        id: get_and_update
        continue-on-error: true
        run: |
          # Get ${{ matrix.subtitle }} Version
          ## Download JSON of API
          API=`echo ${{ matrix.url }} | sed 's/:\/\/github\.com\//:\/\/api.github.com\/repos\//g' | sed 's/$/\/releases/g'`
          wget -O latest.json $API/latest
          wget -O releases.json $API
          
          ## Get Last Stable ${{ matrix.subtitle }}
          LAST_STABLE_VERSION=`sed -n '/"${{ matrix.subtitle }}"/,/version:/p' data/launcher.js | sed -n '$p' | sed 's/^.*:."\|",$//g' | sed 's/\./\\\\./g'`
          
          ## Get Last Dev ${{ matrix.subtitle }}
          LAST_DEV_VERSION=`sed -n '/"${{ matrix.subtitle }}"/,/}/p' data/launcher.js | sed -n '/dev:/,/version:/p' | sed -n '$p' | sed 's/^.*:."\|"$//g' | sed 's/\./\\\\./g'`
          
          ## GET Latest Stable ${{ matrix.subtitle }}
          if [ ${{ matrix.subtitle }} = HMCL ]; then
            LATEST_STABLE_VERSION=`cat releases | sed -n '/"tag_name":."release-/p' | sed -n 1p | sed 's/^.*release-\|",$//g' | sed 's/\./\\\\./g'`
          else
            LATEST_STABLE_VERSION=`cat latest | jq .tag_name | sed 's/^"v\?\|"$//g' | sed 's/\./\\\\./g'`
          fi
          
          ## GET Latest Dev ${{ matrix.subtitle }}
          if [ ${#LAST_DEV_VERSION} != 0 ]; then
            LATEST_DEV_VERSION=`cat releases | sed -n '/"tag_name":/p' | sed -n 1p | sed 's/^.*:."v\?\|",$//g' | sed 's/\./\\\\./g'`
            if [ $LATEST_DEV_VERSION = $LATEST_STABLE_VERSION ]; then
              unset LATEST_DEV_VERSION
            fi
          fi
          
          ## Remove Needless File
          rm latest.json releases.json
          
          
          # Update launcher.js
          ## Modified launcher.js
          if [ ${#LATEST_STABLE_VERSION} != 0 ]; then
            if [ $LAST_STABLE_VERSION != $LATEST_STABLE_VERSION ]; then
              sed -i 's/'"$LAST_STABLE_VERSION"'\(\.[a-z]\|["/-]\)/'"$LATEST_STABLE_VERSION"'\1/g' data/launcher.js
              LATEST_STABLE_VERSION=`echo $LATEST_STABLE_VERSION | sed 's/\\\\././g'`
              CHANGELOG='  ${{ matrix.subtitle }}(stable) to '$LATEST_STABLE_VERSION
            fi
          fi
          if [ ${#LATEST_DEV_VERSION} != 0 ]; then
            if [ $LAST_DEV_VERSION != $LATEST_DEV_VERSION ]; then
              sed -i 's/'"$LAST_DEV_VERSION"'\(\.[a-z]\|["/-]\)/'"$LATEST_DEV_VERSION"'\1/g' data/launcher.js
              LATEST_DEV_VERSION=`echo $LATEST_DEV_VERSION | sed 's/\\\\././g'`
              if [ ${#CHANGELOG} != 0 ]; then
                CHANGELOG=${CHANGELOG}'
            ${{ matrix.subtitle }}(dev) to '$LATEST_DEV_VERSION
              else
                CHANGELOG='  ${{ matrix.subtitle }}(dev) to '$LATEST_DEV_VERSION
              fi
            fi
          fi
          if [ ${#CHANGELOG} != 0 ]; then
            echo ===============================================================
            echo $CHANGELOG
            echo ===============================================================
          fi

          ## Commit Change
          git config --global user.email see_tea@outlook.com
          git config --global user.name teaSummer
          git add .
          git commit -m 'modified: update ${{ matrix.subtitle }}
          
          [Auto] Update Launcher Version:
          '"$CHANGELOG"
      - name: Push Change
        if: ${{ steps.get_and_update.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
