name: Launcher
run-name: Auto Update Version

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  get:
    name: Get Launcher Version
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - subtitle: HMCL
            url: https://github.com/HMCL-dev/HMCL
            device: Windows|macOS|Linux
          - subtitle: HMCL-PE
            url: https://github.com/HMCL-dev/HMCL-PE
            device: Android
          - subtitle: PCL2
            url: https://github.com/Hex-Dragon/PCL2
          - subtitle: FCL
            url: https://github.com/FCL-Team/FoldCraftLauncher
          - subtitle: PojavLauncher
            url: https://github.com/PojavLauncherTeam/PojavLauncher
            device: Android
          - subtitle: PojavLauncher
            url: https://github.com/PojavLauncherTeam/PojavLauncher_iOS
            device: iOS
          - subtitle: XMCL
            url: https://github.com/Voxelum/x-minecraft-launcher
    steps:
      - uses: actions/checkout@main
      - name: Get ${{ matrix.subtitle }} Version & Update launcher.js
        id: get_and_update
        continue-on-error: true
        run: |
          # Get ${{ matrix.subtitle }} Version
          ## Download JSON of API
          API=`echo ${{ matrix.url }} | sed 's/:\/\/github\.com\//:\/\/api.github.com\/repos\//g' | sed 's/$/\/releases/g'`
          wget -O latest.json $API/latest
          wget -O releases.json $API

          ## Copy launcher.js
          if [ '${{ matrix.device }}' ]; then
            DEVICE_LIST=`echo '${{ matrix.device }}' | sed 's/|/\\\\|/g'`
            sed -n '/\('"$DEVICE_LIST"'\)Launcher/,/]/p' data/launcher.js > launcher.js
          else
            cp data/launcher.js launcher.js
          fi
          
          ## Get Last Stable ${{ matrix.subtitle }}
          LAST_STABLE_VERSION=`sed -n '/"${{ matrix.subtitle }}"/,/version:/p' launcher.js | sed -n '$p' | sed 's/^.*:."v\?\|",$//g' | sed 's/\./\\\\./g'`
          
          ## Get Last Dev ${{ matrix.subtitle }}
          LAST_DEV_VERSION=`sed -n '/"${{ matrix.subtitle }}"/,/}/p' launcher.js | sed -n '/dev:/,/version:/p' | sed -n '$p' | sed 's/^.*:."v\?\|"$//g' | sed 's/\./\\\\./g'`
          
          ## GET Latest Stable ${{ matrix.subtitle }}
          if [ '${{ matrix.subtitle }}' = HMCL ]; then
            LATEST_STABLE_VERSION=`cat releases.json | sed -n '/"tag_name":."release-/p' | sed -n 1p | sed 's/^.*release-\|",$//g' | sed 's/\./\\\\./g'`
          else
            LATEST_STABLE_VERSION=`cat latest.json | jq .tag_name | sed 's/^"v\?\|"$//g' | sed 's/\./\\\\./g'`
          fi
          
          ## GET Latest Dev ${{ matrix.subtitle }}
          if [ "$LAST_DEV_VERSION" ]; then
            LATEST_DEV_VERSION=`cat releases.json | sed -n '/"tag_name":/p' | sed -n 1p | sed 's/^.*:."v\?\|",$//g' | sed 's/\./\\\\./g'`
            if [ "$LATEST_DEV_VERSION" = "$LATEST_STABLE_VERSION" ]; then
              unset LATEST_DEV_VERSION
            fi
          fi
          
          ## Remove Needless File
          rm latest.json releases.json launcher.js
          
          
          # Update launcher.js
          ## Modified launcher.js (Local)
          if [ '${{ matrix.device }}' ]; then
            DEVICE_STRING=' [${{ matrix.device }}]'
          else
            DEVICE_STRING=''
          fi
          if [ "$LATEST_STABLE_VERSION" ]; then
            if [ "$LAST_STABLE_VERSION" != "$LATEST_STABLE_VERSION" ]; then
              sed -i 's/'"$LAST_STABLE_VERSION"'\(\.[a-z]\|["/-]\)/'"$LATEST_STABLE_VERSION"'\1/g' data/launcher.js
              LAST_STABLE_VERSION=`echo $LAST_STABLE_VERSION | sed 's/\\\\././g'`
              LATEST_STABLE_VERSION=`echo $LATEST_STABLE_VERSION | sed 's/\\\\././g'`
              CHANGELOG='  ${{ matrix.subtitle }}(stable): '"$LAST_STABLE_VERSION => $LATEST_STABLE_VERSION$DEVICE_STRING"
            fi
          fi
          if [ "$LATEST_DEV_VERSION" ]; then
            if [ "$LAST_DEV_VERSION" != "$LATEST_DEV_VERSION" ]; then
              sed -i 's/'"$LAST_DEV_VERSION"'\(\.[a-z]\|["/-]\)/'"$LATEST_DEV_VERSION"'\1/g' data/launcher.js
              LAST_DEV_VERSION=`echo $LAST_DEV_VERSION | sed 's/\\\\././g'`
              LATEST_DEV_VERSION=`echo $LATEST_DEV_VERSION | sed 's/\\\\././g'`
              if [ "$CHANGELOG" ]; then
                CHANGELOG="${CHANGELOG}"'
            ${{ matrix.subtitle }}(dev): '"$LAST_DEV_VERSION => $LATEST_DEV_VERSION$DEVICE_STRING"
              else
                CHANGELOG='  ${{ matrix.subtitle }}(dev): '"$LAST_DEV_VERSION => $LATEST_DEV_VERSION$DEVICE_STRING"
              fi
            fi
          fi
          if [ "$CHANGELOG" ]; then
            echo ===============================================================
            echo $CHANGELOG
            echo ===============================================================
          fi

          ## Commit Change
          git config --global user.name teaSummer
          git config --global user.email see_tea@outlook.com
          git add .
          git commit -m 'modified: update ${{ matrix.subtitle }}
          
          [Auto] Update Launcher Version:
          '"$CHANGELOG
          (Time: `date +'%F %X %Z'`)"
          git pull --rebase
      - name: Push Change
        if: ${{ steps.get_and_update.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
