name: remote ssh command
on:
  push:
    branches:
      main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command: |
          cd /www/wwwroot/mcisee.top
          ls -a
