on:
  push:
    branches:
      main

jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: deploy (test)
      steps:
        - uses: actions/checkout@v4
        - name: Deploy file
          uses: modern-dev/ftp-mirror@v2
          with:
            server: ${{ secrets.FTP_SERVER }}
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            exclude: ".git/"
